/*
 * DetailedInformationPanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-08-30 19:44:35
 */
package com.yz.rms.client.ui;

import com.nazca.ui.UIUtilities;
import com.nazca.ui.laf.NTitledRoundSideUI;
import com.nazca.usm.model.USMSUser;
import com.nazca.util.StringUtil;
import com.yz.rms.client.util.USMSUserSyncTool;
import com.yz.rms.common.enums.ExpenseFormStateEnums;
import com.yz.rms.common.model.wrap.ExpenseFormWrap;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;

/**
 *
 * @author 上官新建 <shangguanxinjian@yzhtech.com>
 */
public class DetailedInformationPanel extends javax.swing.JPanel {

    private ExpenseFormWrap expenseFormWrap;

    public void setParama(ExpenseFormWrap curexpenseFormWrap) {
	this.expenseFormWrap = curexpenseFormWrap;
	IntComponent(expenseFormWrap);
    }

    /**
     * Creates new form DetailedInformationPanel
     */
    public DetailedInformationPanel() {
	initComponents();
	infoPanel.setUI(new NTitledRoundSideUI("基本信息"));
	feePanel.setUI(new NTitledRoundSideUI("费用信息(元)"));
	auditMarkPanel.setUI(new NTitledRoundSideUI("审核备注信息"));
	likeLabel();

    }

    private void likeLabel() {
	UIUtilities.makeItLikeLabel(expensePersonTxt);
	UIUtilities.makeItLikeLabel(expenseTimeTxt);
	UIUtilities.makeItLikeLabel(expenseProjectTxt);
	UIUtilities.makeItLikeLabel(teamTxt);
	UIUtilities.makeItLikeLabel(expenseFormStateTxt);
	UIUtilities.makeItLikeLabel(creatorTxt);
	UIUtilities.makeItLikeLabel(createTimeTxt);
	UIUtilities.makeItLikeLabel(modifierTxt);
	UIUtilities.makeItLikeLabel(modifyTimeTxt);
	UIUtilities.makeItLikeLabel(cityTrafficTxt);
	UIUtilities.makeItLikeLabel(travelMealsTxt);
	UIUtilities.makeItLikeLabel(booksMaterialsTxt);
	UIUtilities.makeItLikeLabel(travelAllowanceTxt);
	UIUtilities.makeItLikeLabel(cityGasolineTxt);
	UIUtilities.makeItLikeLabel(travelAccommodationTxt);
	UIUtilities.makeItLikeLabel(copyBindTxt);
	UIUtilities.makeItLikeLabel(travelTrafficTxt);
	UIUtilities.makeItLikeLabel(entertainTxt);
	UIUtilities.makeItLikeLabel(spacePageTxt);
	UIUtilities.makeItLikeLabel(materialTxt);
	UIUtilities.makeItLikeLabel(conferencesTxt);
	UIUtilities.makeItLikeLabel(trainTxt);
	UIUtilities.makeItLikeLabel(fieldOperationTxt);
	UIUtilities.makeItLikeLabel(officeSuppliesTxt);
	UIUtilities.makeItLikeLabel(telephoneBillTxt);
	UIUtilities.makeItLikeLabel(postageTxt);
	UIUtilities.makeItLikeLabel(totalTxt);
	UIUtilities.makeItLikeLabel(memoTxa);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        expensePersonLabel = new javax.swing.JLabel();
        expensePersonTxt = new javax.swing.JTextField();
        expenseTimeLabel = new javax.swing.JLabel();
        expenseTimeTxt = new javax.swing.JTextField();
        expenseProjectTxt = new javax.swing.JTextField();
        expenseProjectLabel = new javax.swing.JLabel();
        teamLabel = new javax.swing.JLabel();
        teamTxt = new javax.swing.JTextField();
        expenseFormStateTxt = new javax.swing.JTextField();
        expenseFormStateLabel = new javax.swing.JLabel();
        creatorTxt = new javax.swing.JTextField();
        creatorLabel = new javax.swing.JLabel();
        createTimeLabel = new javax.swing.JLabel();
        createTimeTxt = new javax.swing.JTextField();
        modifierLabel = new javax.swing.JLabel();
        modifierTxt = new javax.swing.JTextField();
        modifyTimeLabel = new javax.swing.JLabel();
        modifyTimeTxt = new javax.swing.JTextField();
        feePanel = new javax.swing.JPanel();
        cityTrafficLabel = new javax.swing.JLabel();
        cityTrafficTxt = new javax.swing.JTextField();
        travelMealsLabel = new javax.swing.JLabel();
        travelMealsTxt = new javax.swing.JTextField();
        booksMaterialsLabel = new javax.swing.JLabel();
        booksMaterialsTxt = new javax.swing.JTextField();
        travelAllowanceLabel = new javax.swing.JLabel();
        travelAllowanceTxt = new javax.swing.JTextField();
        cityGasolineTxt = new javax.swing.JTextField();
        cityGasolineLabel = new javax.swing.JLabel();
        travelAccommodationLabel = new javax.swing.JLabel();
        travelAccommodationTxt = new javax.swing.JTextField();
        copyBindLabel = new javax.swing.JLabel();
        copyBindTxt = new javax.swing.JTextField();
        travelTrafficLabel = new javax.swing.JLabel();
        travelTrafficTxt = new javax.swing.JTextField();
        entertainLabel = new javax.swing.JLabel();
        entertainTxt = new javax.swing.JTextField();
        spacePageLabel = new javax.swing.JLabel();
        spacePageTxt = new javax.swing.JTextField();
        materialLabel = new javax.swing.JLabel();
        materialTxt = new javax.swing.JTextField();
        conferencesTxt = new javax.swing.JTextField();
        conferencesLabel = new javax.swing.JLabel();
        trainLabel = new javax.swing.JLabel();
        trainTxt = new javax.swing.JTextField();
        fieldOperationLabel = new javax.swing.JLabel();
        fieldOperationTxt = new javax.swing.JTextField();
        officeSuppliesLabel = new javax.swing.JLabel();
        officeSuppliesTxt = new javax.swing.JTextField();
        telephoneBillTxt = new javax.swing.JTextField();
        telephoneBillLabel = new javax.swing.JLabel();
        postageLabel = new javax.swing.JLabel();
        postageTxt = new javax.swing.JTextField();
        totalTxt = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        auditMarkPanel = new javax.swing.JPanel();
        memoTxa = new javax.swing.JTextArea();

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        setPreferredSize(new java.awt.Dimension(324, 1132));
        setLayout(new java.awt.BorderLayout());

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new com.nazca.ui.layout.BoxLayout2());

        infoPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));

        expensePersonLabel.setText("报销人员：");

        expenseTimeLabel.setText("报销时间：");

        expenseProjectLabel.setText("报销项目：");

        teamLabel.setText("所在团队：");

        teamTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamTxtActionPerformed(evt);
            }
        });

        expenseFormStateLabel.setText("报销单状态：");

        creatorLabel.setText("创建人：");

        createTimeLabel.setText("创建时间：");

        modifierLabel.setText("最近修改人：");

        modifyTimeLabel.setText("修改时间：");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expensePersonLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expenseTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expenseProjectLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teamLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expenseFormStateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(creatorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifierLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifyTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expensePersonTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(expenseTimeTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expenseProjectTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teamTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expenseFormStateTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(creatorTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createTimeTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifierTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifyTimeTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expensePersonLabel)
                    .addComponent(expensePersonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expenseTimeLabel)
                    .addComponent(expenseTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expenseProjectLabel)
                    .addComponent(expenseProjectTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamLabel)
                    .addComponent(teamTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expenseFormStateLabel)
                    .addComponent(expenseFormStateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creatorLabel)
                    .addComponent(creatorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createTimeLabel)
                    .addComponent(createTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifierLabel)
                    .addComponent(modifierTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyTimeLabel)
                    .addComponent(modifyTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(infoPanel);

        feePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));

        cityTrafficLabel.setText("市内交通费：");

        travelMealsLabel.setText("出差餐费：");

        booksMaterialsLabel.setText("图书资料费：");

        travelAllowanceLabel.setText("出差补助费：");

        cityGasolineLabel.setText("市内汽油费：");

        travelAccommodationLabel.setText("出差住宿费：");

        copyBindLabel.setText("复印装订费：");

        travelTrafficLabel.setText("出差交通费：");

        travelTrafficTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelTrafficTxtActionPerformed(evt);
            }
        });

        entertainLabel.setText("市内招待费：");

        spacePageLabel.setText("版面费：");

        materialLabel.setText("材料费：");

        conferencesLabel.setText("会议费：");

        trainLabel.setText("培训费：");

        fieldOperationLabel.setText("外勤费：");

        officeSuppliesLabel.setText("办公用品费：");

        telephoneBillLabel.setText("电话费：");

        postageLabel.setText("邮费：");

        totalLabel.setText("总计：");

        javax.swing.GroupLayout feePanelLayout = new javax.swing.GroupLayout(feePanel);
        feePanel.setLayout(feePanelLayout);
        feePanelLayout.setHorizontalGroup(
            feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityTrafficLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(travelMealsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(booksMaterialsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(travelAllowanceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cityGasolineLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(travelAccommodationLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(copyBindLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(travelTrafficLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(entertainLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spacePageLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(materialLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conferencesLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trainLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldOperationLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(officeSuppliesLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telephoneBillLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(postageLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityTrafficTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(travelMealsTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(booksMaterialsTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(travelAllowanceTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(cityGasolineTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(travelAccommodationTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(copyBindTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(travelTrafficTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(entertainTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(spacePageTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(materialTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(conferencesTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(trainTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(fieldOperationTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(officeSuppliesTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(telephoneBillTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(postageTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(totalTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        feePanelLayout.setVerticalGroup(
            feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feePanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityTrafficLabel)
                    .addComponent(cityTrafficTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(travelMealsLabel)
                    .addComponent(travelMealsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booksMaterialsLabel)
                    .addComponent(booksMaterialsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(travelAllowanceLabel)
                    .addComponent(travelAllowanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityGasolineLabel)
                    .addComponent(cityGasolineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(travelAccommodationLabel)
                    .addComponent(travelAccommodationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyBindLabel)
                    .addComponent(copyBindTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(travelTrafficLabel)
                    .addComponent(travelTrafficTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entertainLabel)
                    .addComponent(entertainTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spacePageLabel)
                    .addComponent(spacePageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialLabel)
                    .addComponent(materialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conferencesLabel)
                    .addComponent(conferencesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainLabel)
                    .addComponent(trainTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldOperationLabel)
                    .addComponent(fieldOperationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(officeSuppliesLabel)
                    .addComponent(officeSuppliesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneBillLabel)
                    .addComponent(telephoneBillTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postageLabel)
                    .addComponent(postageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(feePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(feePanel);

        auditMarkPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        auditMarkPanel.setLayout(new java.awt.GridBagLayout());

        memoTxa.setColumns(20);
        memoTxa.setLineWrap(true);
        memoTxa.setRows(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 33, 1, 34);
        auditMarkPanel.add(memoTxa, gridBagConstraints);

        jPanel1.add(auditMarkPanel);

        jScrollPane4.setViewportView(jPanel1);

        add(jScrollPane4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void travelTrafficTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelTrafficTxtActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_travelTrafficTxtActionPerformed

    private void teamTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamTxtActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_teamTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel auditMarkPanel;
    private javax.swing.JLabel booksMaterialsLabel;
    private javax.swing.JTextField booksMaterialsTxt;
    private javax.swing.JLabel cityGasolineLabel;
    private javax.swing.JTextField cityGasolineTxt;
    private javax.swing.JLabel cityTrafficLabel;
    private javax.swing.JTextField cityTrafficTxt;
    private javax.swing.JLabel conferencesLabel;
    private javax.swing.JTextField conferencesTxt;
    private javax.swing.JLabel copyBindLabel;
    private javax.swing.JTextField copyBindTxt;
    private javax.swing.JLabel createTimeLabel;
    private javax.swing.JTextField createTimeTxt;
    private javax.swing.JLabel creatorLabel;
    private javax.swing.JTextField creatorTxt;
    private javax.swing.JLabel entertainLabel;
    private javax.swing.JTextField entertainTxt;
    private javax.swing.JLabel expenseFormStateLabel;
    private javax.swing.JTextField expenseFormStateTxt;
    private javax.swing.JLabel expensePersonLabel;
    private javax.swing.JTextField expensePersonTxt;
    private javax.swing.JLabel expenseProjectLabel;
    private javax.swing.JTextField expenseProjectTxt;
    private javax.swing.JLabel expenseTimeLabel;
    private javax.swing.JTextField expenseTimeTxt;
    private javax.swing.JPanel feePanel;
    private javax.swing.JLabel fieldOperationLabel;
    private javax.swing.JTextField fieldOperationTxt;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel materialLabel;
    private javax.swing.JTextField materialTxt;
    private javax.swing.JTextArea memoTxa;
    private javax.swing.JLabel modifierLabel;
    private javax.swing.JTextField modifierTxt;
    private javax.swing.JLabel modifyTimeLabel;
    private javax.swing.JTextField modifyTimeTxt;
    private javax.swing.JLabel officeSuppliesLabel;
    private javax.swing.JTextField officeSuppliesTxt;
    private javax.swing.JLabel postageLabel;
    private javax.swing.JTextField postageTxt;
    private javax.swing.JLabel spacePageLabel;
    private javax.swing.JTextField spacePageTxt;
    private javax.swing.JLabel teamLabel;
    private javax.swing.JTextField teamTxt;
    private javax.swing.JLabel telephoneBillLabel;
    private javax.swing.JTextField telephoneBillTxt;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JLabel trainLabel;
    private javax.swing.JTextField trainTxt;
    private javax.swing.JLabel travelAccommodationLabel;
    private javax.swing.JTextField travelAccommodationTxt;
    private javax.swing.JLabel travelAllowanceLabel;
    private javax.swing.JTextField travelAllowanceTxt;
    private javax.swing.JLabel travelMealsLabel;
    private javax.swing.JTextField travelMealsTxt;
    private javax.swing.JLabel travelTrafficLabel;
    private javax.swing.JTextField travelTrafficTxt;
    // End of variables declaration//GEN-END:variables

    private void IntComponent(ExpenseFormWrap expenseFormWrap) {
	if (expenseFormWrap != null) {
	    setPanelVisible(true);
	    /**
	     * 报销项目
	     */
	    if (expenseFormWrap.getProjectName() != null) {
		expenseProjectLabel.setVisible(true);
		expenseProjectTxt.setVisible(true);
		expenseProjectTxt.setText(expenseFormWrap.getProjectName());
	    } else {
		expenseProjectTxt.setVisible(false);
		expenseProjectTxt.setVisible(false);
	    }
	    /**
	     * 所在团队
	     */
	    if (expenseFormWrap.getTeamName() != null) {
		teamLabel.setVisible(true);
		teamTxt.setVisible(true);
		teamTxt.setText(expenseFormWrap.getTeamName());
	    } else {
		teamLabel.setVisible(true);
		teamTxt.setVisible(true);
	    }
	    if (expenseFormWrap.getExpenseForm() != null) {
		/**
		 * 备注
		 */
		if (!StringUtil.isEmpty(expenseFormWrap.getExpenseForm().getMemo())) {
		    auditMarkPanel.setVisible(true);
		    memoTxa.setText(expenseFormWrap.getExpenseForm().getMemo());
		} else {
		    auditMarkPanel.setVisible(false);
		}
		/**
		 * 报销人员
		 */
		if (!StringUtil.isEmpty(expenseFormWrap.getExpenseForm().getExpensePersonId())) {
		    expensePersonLabel.setVisible(true);
		    expensePersonTxt.setVisible(true);
		    USMSUser user = USMSUserSyncTool.getInstance().getUserById(expenseFormWrap.getExpenseForm().getExpensePersonId());
		    expensePersonTxt.setText(user.getName());
		} else {
		    expensePersonLabel.setVisible(false);
		    expensePersonTxt.setVisible(false);
		}
		/**
		 * 报销时间
		 */
		if (expenseFormWrap.getExpenseForm().getExpenseTime() != null) {
		    expenseTimeLabel.setVisible(true);
		    expenseTimeTxt.setVisible(true);
		    expenseTimeTxt.setText(new SimpleDateFormat("yyyy-MM-dd").format(expenseFormWrap.getExpenseForm().getExpenseTime()));
		} else {
		    expenseTimeLabel.setVisible(false);
		    expenseTimeTxt.setVisible(false);
		}
		/**
		 * 报销单状态
		 */
		if (expenseFormWrap.getExpenseForm().getState() != null) {
		    if (expenseFormWrap.getExpenseForm().isPassState()) {
			expenseFormStateLabel.setVisible(true);
			expenseFormStateTxt.setVisible(true);
			expenseFormStateTxt.setText(expenseFormWrap.getExpenseForm().getState().toString());
		    } else {
			expenseFormStateLabel.setVisible(true);
			expenseFormStateTxt.setVisible(true);
			expenseFormStateTxt.setText(ExpenseFormStateEnums.deny.toString());
		    }
		} else {
		    expenseFormStateLabel.setVisible(false);
		    expenseFormStateTxt.setVisible(false);
		}
		/**
		 * 创建人
		 */
		if (!StringUtil.isEmpty(expenseFormWrap.getExpenseForm().getCreator())) {
		    creatorLabel.setVisible(true);
		    creatorTxt.setVisible(true);
		    creatorTxt.setText(getUserNameById(expenseFormWrap.getExpenseForm().getCreator()).getName());
		} else {
		    creatorLabel.setVisible(false);
		    creatorTxt.setVisible(false);
		}
		/**
		 * 创建时间
		 */
		if (expenseFormWrap.getExpenseForm().getCreateTime() != null) {
		    createTimeLabel.setVisible(true);
		    createTimeTxt.setVisible(true);
		    createTimeTxt.setText(new SimpleDateFormat("yyyy-MM-dd").format(expenseFormWrap.getExpenseForm().getCreateTime()));
		} else {
		    createTimeLabel.setVisible(false);
		    createTimeTxt.setVisible(false);
		}
		/**
		 * 修改人
		 */
		if (!StringUtil.isEmpty(expenseFormWrap.getExpenseForm().getModifier())) {
		    modifierLabel.setVisible(true);
		    modifierTxt.setVisible(true);
//		    modifierTxt.setText(expenseFormWrap.getExpenseForm().getModifier());
		    modifierTxt.setText(getUserNameById(expenseFormWrap.getExpenseForm().getModifier()).getName());
		} else {
		    modifierLabel.setVisible(false);
		    modifierTxt.setVisible(false);
		}
		/**
		 * 最近修改时间
		 */
		if (expenseFormWrap.getExpenseForm().getModifyTime() != null) {
		    modifyTimeLabel.setVisible(true);
		    modifyTimeTxt.setVisible(true);
		    modifyTimeTxt.setText(new SimpleDateFormat("yyyy-MM-dd").format(expenseFormWrap.getExpenseForm().getModifyTime()));
		} else {
		    modifyTimeLabel.setVisible(false);
		    modifyTimeTxt.setVisible(false);
		}
		/**
		 * 市内交通
		 */
		if (expenseFormWrap.getExpenseForm().getCityTraffic() != null) {
		    cityTrafficLabel.setVisible(true);
		    cityTrafficTxt.setVisible(true);
		    cityTrafficTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getCityTraffic()));
		} else {
		    cityTrafficLabel.setVisible(false);
		    cityTrafficTxt.setVisible(false);
		}
		/**
		 * 图书资料
		 */
		if (expenseFormWrap.getExpenseForm().getBooksMaterials() != null) {
		    booksMaterialsLabel.setVisible(true);
		    booksMaterialsTxt.setVisible(true);
		    booksMaterialsTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getBooksMaterials()));
		} else {
		    booksMaterialsLabel.setVisible(false);
		    booksMaterialsTxt.setVisible(false);
		}
		/**
		 * 市内汽油
		 */
		if (expenseFormWrap.getExpenseForm().getCityGasoline() != null) {
		    cityGasolineLabel.setVisible(true);
		    cityGasolineTxt.setVisible(true);
		    cityGasolineTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getCityGasoline()));
		} else {
		    cityGasolineLabel.setVisible(false);
		    cityGasolineTxt.setVisible(false);
		}
		/**
		 * 复印装订
		 */
		if (expenseFormWrap.getExpenseForm().getCopyBind() != null) {
		    copyBindLabel.setVisible(true);
		    copyBindTxt.setVisible(true);
		    copyBindTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getCopyBind()));
		} else {
		    copyBindLabel.setVisible(false);
		    copyBindTxt.setVisible(false);
		}
		/**
		 * 市内招待
		 */
		if (expenseFormWrap.getExpenseForm().getEntertain() != null) {
		    entertainLabel.setVisible(true);
		    entertainTxt.setVisible(true);
		    entertainTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getEntertain()));
		} else {
		    entertainLabel.setVisible(false);
		    entertainTxt.setVisible(false);
		}
		/**
		 * 材料费
		 */
		if (expenseFormWrap.getExpenseForm().getMaterial() != null) {
		    materialLabel.setVisible(true);
		    materialTxt.setVisible(true);
		    materialTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getMaterial()));
		} else {
		    materialLabel.setVisible(false);
		    materialTxt.setVisible(false);
		}
		/**
		 * 培训费
		 */
		if (expenseFormWrap.getExpenseForm().getTrain() != null) {
		    trainLabel.setVisible(true);
		    trainTxt.setVisible(true);
		    trainTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getTrain()));
		} else {
		    trainLabel.setVisible(false);
		    trainTxt.setVisible(false);
		}
		/**
		 * 办公用品费
		 */
		if (expenseFormWrap.getExpenseForm().getOfficeSupplies() != null) {
		    officeSuppliesLabel.setVisible(true);
		    officeSuppliesTxt.setVisible(true);
		    officeSuppliesTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getOfficeSupplies()));
		} else {
		    officeSuppliesLabel.setVisible(false);
		    officeSuppliesTxt.setVisible(false);
		}
		/**
		 * 电话费
		 */
		if (expenseFormWrap.getExpenseForm().getTelephoneBill() != null) {
		    telephoneBillLabel.setVisible(true);
		    telephoneBillTxt.setVisible(true);
		    telephoneBillTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getTelephoneBill()));
		} else {
		    telephoneBillLabel.setVisible(false);
		    telephoneBillTxt.setVisible(false);
		}
		/**
		 * 邮费
		 */
		if (expenseFormWrap.getExpenseForm().getPostage() != null) {
		    postageLabel.setVisible(true);
		    postageTxt.setVisible(true);
		    postageTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getPostage()));
		} else {
		    postageLabel.setVisible(false);
		    postageTxt.setVisible(false);
		}
		/**
		 * 出差住宿费
		 */
		if (expenseFormWrap.getExpenseForm().getTravelAccommodation() != null) {
		    travelAccommodationLabel.setVisible(true);
		    travelAccommodationTxt.setVisible(true);
		    travelAccommodationTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getTravelAccommodation()));;
		} else {
		    travelAccommodationLabel.setVisible(false);
		    travelAccommodationTxt.setVisible(false);
		}
		/**
		 * 出差交通费
		 */
		if (expenseFormWrap.getExpenseForm().getTravelTraffic() != null) {
		    travelTrafficLabel.setVisible(true);
		    travelTrafficTxt.setVisible(true);
		    travelTrafficTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getTravelTraffic()));
		} else {
		    travelTrafficLabel.setVisible(false);
		    travelTrafficTxt.setVisible(false);
		}
		/**
		 * 出差餐费
		 */
		if (expenseFormWrap.getExpenseForm().getTravelMeals() != null) {
		    travelMealsLabel.setVisible(true);
		    travelMealsTxt.setVisible(true);
		    travelMealsTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getTravelMeals()));
		} else {
		    travelMealsLabel.setVisible(false);
		    travelMealsTxt.setVisible(false);
		}
		/**
		 * 差旅补助
		 */
		if (expenseFormWrap.getExpenseForm().getTravelAllowance() != null) {
		    travelAllowanceLabel.setVisible(true);
		    travelAllowanceTxt.setVisible(true);
		    travelAllowanceTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getTravelAllowance()));
		} else {
		    travelAllowanceLabel.setVisible(false);
		    travelAllowanceTxt.setVisible(false);
		}
		/**
		 * 版面费
		 */
		if (expenseFormWrap.getExpenseForm().getSpacePage() != null) {
		    spacePageLabel.setVisible(true);
		    spacePageTxt.setVisible(true);
		    spacePageTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getSpacePage()));
		} else {
		    spacePageLabel.setVisible(false);
		    spacePageTxt.setVisible(false);
		}
		/**
		 * 会议费
		 */
		if (expenseFormWrap.getExpenseForm().getConferences() != null) {
		    conferencesLabel.setVisible(true);
		    conferencesTxt.setVisible(true);
		    conferencesTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getConferences()));
		} else {
		    conferencesLabel.setVisible(false);
		    conferencesTxt.setVisible(false);
		}
		/**
		 * 外勤费
		 */
		if (expenseFormWrap.getExpenseForm().getFieldOperation() != null) {
		    fieldOperationLabel.setVisible(true);
		    fieldOperationTxt.setVisible(true);
		    fieldOperationTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getFieldOperation()));
		} else {
		    fieldOperationLabel.setVisible(false);
		    fieldOperationTxt.setVisible(false);
		}
		/**
		 * 合计
		 */
		if (expenseFormWrap.getExpenseForm().getExpenseTotal() != null) {
		    totalLabel.setVisible(true);
		    totalTxt.setVisible(true);
		    totalTxt.setText(Double.toString(expenseFormWrap.getExpenseForm().getExpenseTotal()));
		} else {
		    totalLabel.setVisible(false);
		    totalTxt.setVisible(false);
		}

	    }
	} else {
	    setPanelVisible(false);
	}
    }

    private void setPanelVisible(boolean flag) {
	infoPanel.setVisible(flag);
	feePanel.setVisible(flag);
	auditMarkPanel.setVisible(flag);
    }

    private USMSUser getUserNameById(String userId) {
	USMSUser user = USMSUserSyncTool.getInstance().getUserById(userId);
	return user;
    }
}
