/*
 * AddOrUpdateTeamPanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-08-08 11:39:03
 */
package com.yz.rms.client.ui.team;

import com.nazca.ui.NComponentStyleTool;
import com.nazca.ui.NInternalDiag;
import com.nazca.ui.NInternalDiagListener;
import com.nazca.usm.model.USMSUser;
import com.nazca.util.StringUtil;
import com.nazca.util.TimeFairy;
import com.yz.rms.client.ClientContext;
import com.yz.rms.client.agent.team.AddTeamAgent;
import com.yz.rms.client.agent.team.ModifyTeamAgent;
import com.yz.rms.client.ui.OKCancelPanelListener;
import com.yz.rms.client.listener.AgentListener;
import com.yz.rms.client.util.ResourceUtil;
import com.yz.rms.common.consts.table.TeamTableConsts;
import com.yz.rms.common.model.Team;
import java.util.UUID;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;

/**
 * 添加或修改团队弹出面板
 *
 * @author 赵洪坤 <zhaohongkun@yzhtech.com>
 */
public class AddOrUpdateTeamPanel extends javax.swing.JPanel {

    private boolean addModel;
    private AddTeamAgent addTeamAgent;
    private ModifyTeamAgent modifyTeamAgent;
    private Team team;
    private Team curTeam;
    USMSUser curUser = ClientContext.getUser();

    /**
     * Creates new form AddOR
     */
    public AddOrUpdateTeamPanel() {
        initComponents();
        initAgentAndListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        teamNameTxFd = new javax.swing.JTextField();
        oKCancelPanel1 = new com.yz.rms.client.ui.OKCancelPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));

        jLabel1.setText("团队名称：");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(teamNameTxFd, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(teamNameTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
        add(oKCancelPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    public void setIsAdd(boolean isAdd) {
        this.addModel = isAdd;
    }

    public void initPanelContent(Team curTeam) {
        this.curTeam = curTeam;
        teamNameTxFd.setText(curTeam.getTeamName());
    }

    private void initAgentAndListener() {
        addTeamAgent = new AddTeamAgent();
        addTeamAgent.addListener(addOrModifyTeamAgentListener);
        modifyTeamAgent = new ModifyTeamAgent();
        modifyTeamAgent.addListener(addOrModifyTeamAgentListener);
        oKCancelPanel1.addOKCancelListener(new OKCancelPanelListener() {
            @Override
            public void onOKClicked() {
                NComponentStyleTool.normalStyle(teamNameTxFd);
                if (analysisContents()) {
                    if (addModel) {
                        team = new Team();
                        team.setTeamId(UUID.randomUUID().toString());
                        team.setTeamName(teamNameTxFd.getText());
                        team.setCreator(curUser.getName());
                        team.setModifier(curUser.getName());
                        addTeamAgent.setParameter(team);
                        addTeamAgent.start();
                    } else {
                        curTeam.setTeamName(teamNameTxFd.getText());
                        curTeam.setModifier(curUser.getName());
                        modifyTeamAgent.setParameter(curTeam);
                        modifyTeamAgent.start();
                    }
                }
            }

            @Override
            public void onCancelClicked() {
                NInternalDiag<Team, JComponent> diag = NInternalDiag.findNInternalDiag(
                        AddOrUpdateTeamPanel.this);
                diag.hideDiag();
            }
        });

    }

    public Team showMe(JComponent parent) {
        NInternalDiag<Team, JComponent> diag = null;
        if (addModel) {
            diag = new NInternalDiag<>("添加团队", ResourceUtil.buildImageIcon("32.png"), this);
        } else {
            diag = new NInternalDiag<>("修改团队", ResourceUtil.buildImageIcon("32.png"), this);
        }
        diag.addNInternalDiagListener(new NInternalDiagListener() {

            @Override
            public void onClosing(NInternalDiag nid) {
            }

            @Override
            public void onClosed(NInternalDiag nid) {
            }

            @Override
            public void onShowingDone(NInternalDiag nid) {
                teamNameTxFd.requestFocusInWindow();
            }
        });
        return diag.showInternalDiag(parent, NInternalDiag.INIT_SIZE_MODE_PREFERED);
    }

    boolean analysisContents() {
        boolean flag = true;
        if (StringUtil.isEmpty(teamNameTxFd.getText().trim())) {
            flag = false;
            oKCancelPanel1.gotoErrorMode("团队名称不能为空");
            NComponentStyleTool.errorStyle(teamNameTxFd);
        } else if (teamNameTxFd.getText().trim().length() > TeamTableConsts.FIELD_TEAM_NAME.getLength()) {
            flag = false;
            oKCancelPanel1.gotoErrorMode("团队名称太长");
            NComponentStyleTool.errorStyle(teamNameTxFd);
        }
        return flag;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.yz.rms.client.ui.OKCancelPanel oKCancelPanel1;
    private javax.swing.JTextField teamNameTxFd;
    // End of variables declaration//GEN-END:variables
     AgentListener<Team> addOrModifyTeamAgentListener = new AgentListener<Team>() {
        @Override
        public void onStarted(long seq) {
            teamNameTxFd.setEnabled(false);
            if (addModel) {
                oKCancelPanel1.gotoWaitMode("正在添加...");
            } else {
                oKCancelPanel1.gotoWaitMode("正在修改...");
            }
        }

        @Override
        public void onSucceeded(Team result, long seq) {
            teamNameTxFd.setEnabled(true);
            if (addModel) {
                oKCancelPanel1.gotoSuccessMode("添加成功");
            } else {
                oKCancelPanel1.gotoSuccessMode("修改成功");
            }
            new Thread() {
                @Override
                public void run() {
                    new TimeFairy().sleepIfNecessary();
                    SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                            NInternalDiag<Team, JComponent> diag = NInternalDiag.findNInternalDiag(
                                    AddOrUpdateTeamPanel.this);
                            diag.hideDiag(result);
                        }
                    });
                }
            }.start();
        }

        @Override
        public void onFailed(String errMsg, int errCode, long seq) {
            teamNameTxFd.setEnabled(true);
            oKCancelPanel1.gotoErrorMode(errMsg, errCode);
        }
    };
}
