/*
 * ExpenseFormMgmtPanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-08-10 13:20:02
 */
package com.yz.rms.client.ui.expenseform;

import com.nazca.ui.NSwitchPanel;
import com.yz.rms.client.ClientContext;
import com.yz.rms.common.consts.ProjectConst;
import com.yz.rms.common.enums.ExpenseRoleEnum;
import java.awt.Component;
import javax.swing.JToggleButton;

/**
 *
 * @author 张琪 <zhangqi@yzhtech.com>
 */
public class ExpenseFormMgmtPanel extends javax.swing.JPanel {
    
    private ExpenseFormTabPanel expenseFormTabPane = null;
    private ExpenseFormAuditPanel expenseFormAuditPane = null;

    /**
     * Creates new form ExpenseFormMgmtPanel
     */
    public ExpenseFormMgmtPanel() {
        initComponents();
        initUI();
        expenseFormAuditBtn.setVisible(false);
        if(ClientContext.getUser().hasRole(ProjectConst.USMS_MODULE_ID, ExpenseRoleEnum.PM.name())){
            expenseFormAuditBtn.setVisible(true);
        }
        if(ClientContext.getUser().hasRole(ProjectConst.USMS_MODULE_ID, ExpenseRoleEnum.CEO.name())){
            expenseFormAuditBtn.setVisible(true);
        }
        if(ClientContext.getUser().hasRole(ProjectConst.USMS_MODULE_ID, ExpenseRoleEnum.HR.name())){
            expenseFormAuditBtn.setVisible(true);
        }
    }
    
    
     private void initUI() {
        //我的报销单
        expenseFormTabPane = new ExpenseFormTabPanel();
        //审核报销单
        expenseFormAuditPane = new ExpenseFormAuditPanel();
        //设置默认选中项
        for (Component c : nNavToolBar1.getComponents()) {
            if (c.isVisible()) {
                ((JToggleButton) c).doClick();
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        nNavToolBar1 = new com.nazca.ui.NNavToolBar();
        myExpenseFormBtn = new javax.swing.JToggleButton();
        expenseFormAuditBtn = new javax.swing.JToggleButton();
        nSwitchPanel1 = new com.nazca.ui.NSwitchPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        nNavToolBar1.setRollover(true);

        buttonGroup1.add(myExpenseFormBtn);
        myExpenseFormBtn.setText("我的报销单");
        myExpenseFormBtn.setFocusable(false);
        myExpenseFormBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myExpenseFormBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myExpenseFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myExpenseFormBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(myExpenseFormBtn);

        buttonGroup1.add(expenseFormAuditBtn);
        expenseFormAuditBtn.setText("报销单审核");
        expenseFormAuditBtn.setFocusable(false);
        expenseFormAuditBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        expenseFormAuditBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        expenseFormAuditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseFormAuditBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(expenseFormAuditBtn);

        jPanel3.add(nNavToolBar1, java.awt.BorderLayout.PAGE_START);
        jPanel3.add(nSwitchPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void myExpenseFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myExpenseFormBtnActionPerformed
        nSwitchPanel1.switchTo(new ExpenseFormTabPanel(), NSwitchPanel.FROM_LEFT);
    }//GEN-LAST:event_myExpenseFormBtnActionPerformed

    private void expenseFormAuditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseFormAuditBtnActionPerformed
        nSwitchPanel1.switchTo(new ExpenseFormAuditPanel(), NSwitchPanel.FROM_LEFT);
    }//GEN-LAST:event_expenseFormAuditBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton expenseFormAuditBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton myExpenseFormBtn;
    private com.nazca.ui.NNavToolBar nNavToolBar1;
    private com.nazca.ui.NSwitchPanel nSwitchPanel1;
    // End of variables declaration//GEN-END:variables
}
